#!/usr/bin/env bash
# install nginx on web-01 server according to specs

sudo apt update
sudo apt install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
