#!/usr/bin/env bash
# install nginx on web-01 server according to specs

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "301 Moved Permanently" > /var/www/html/index.html
sed -i '38i\rewrite ^/redirect_me https://www.google.com permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
