#!/usr/bin/env bash
# install nginx on web-01 server according to specs

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Ceci n'est pas une page" | sudo tee -a /var/www/html/index.html
sudo bash -c "sed -i '39i\\error_page 404 /error_404.html;' /etc/nginx/sites-available/default"
sudo service nginx restart
