#!/usr/bin/env bash
# install and configure HAproxy on lb-01 server
# should send traffic to web-01 and web-02
# should use roundrobin algorithm and can be managed via init script

balancer="\
frontend haproxy_balancer
	bind *:80
	mode http
	default_backend webservers

backend webservers
	balance roundrobin
	server 134815-web-01 54.83.167.170 check
	server 134815-web-02 54.221.184.104 check
"
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update
apt-get -y install haproxy=2.5.\*

# installing HAProxy
apt-get -y install haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" >> /etc/haproxy/haproxy.cfg
service haproxy restart
